spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://localhost:33306/oas-sample?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:/flyway
    baseline-on-migrate: true
    sql-migration-suffixes: sql
    baseline-version: 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: INFO